### PR TITLE
Create Guidebook.vue

### PR DESCRIPTION
**Pull request by Lorcanomahony1**

### CODE REVIEW

**Comment by ReyeMe** [comment]
Bad code, full of place holders

**Comment by Lorcanomahony1** [comment]
> Bad code, full of place holders

Thanks for the feedback, but i'm not sure what you mean when you say it is full of placeholders, by placeholders do you actually mean element selectors?  Because the design was based off of this image that was sent to me by Cerx which contains a lot of placeholers https://lorcanomahony.imgbb.com/

**Comment by Lorcanomahony1** [comment]
https://i.ibb.co/bm42hhw/image4493.png

**Comment by ReyeMe** [comment]
Yeah I mean those sections, those should be defined by using elements, instead of statically placing them in the code directly.

**Pull request closed without merging**
